name = '20210802_train/'
adam = False  # 改为true试一下
artifact_alias = 'latest'
batch_size = 16  # 默认16
bbox_interval = -1
bucket = ''
cache_images = False
cfg = 'yolov5_official/yamls/yolov5s.yaml'
cfga = 'yolov5_official/yamls/v5s_transformer.yaml'  # 如果使用 attention的话就使用这个cfg
data = 'yolov5_official/yamls/Algae.yaml'
device = 'cpu'
entity = None
epochs = 300  # 默认300
evolve = False
exist_ok = False
hyp = 'yolov5_official/yamls/hyp.scratch.yaml'
image_weights = False
# img_size = [640, 640] # 直接写640就好
img_size = 640
label_smoothing = 0.2
linear_lr = False
local_rank = -1
multi_scale = True
noautoanchor = False
nosave = False
notest = False
project = 'runs/train'
quad = False
rect = False
resume = False
save_period = 5
single_cls = False
sync_bn = False
upload_dataset = False
weights = 'result/model/yolov5s.pt'
workers = 0
save_dir = 'yolov5_official/result/'
save_image_dir = 'images/'
use_gpu = False
eval_interval = 5
pretrained = True
world_size = 1
use_attention = False